# Generated by Django 4.2.6 on 2023-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personaje', models.CharField(max_length=50)),
                ('Saga', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
